return {
	
	CustomProcessReceipt = false, -- if you have another process receipt function in your game code then set this to true 
	TopDonorsListSize = 25, -- this is the amount of top donors shown on the leaderboard; can be 10 - 100
	Products = { -- these are the developer product ids for the donation products, all you need to do is put the product id
		1859497644,
		1859497665,
		1859497693,
		1859497728,
		1859497843,
		1859497883,
		1859497939,
		1859497961,
		1859498044,
		1859498121,
		1859498175,
		1859498240,
	},
	
	-- character model emotes contains animations that the #1 top donor CharacterModel will have (one picked randomly every leaderboard refresh to play)
	
}	