local Settings = {
	OwnerId = 5321643116,
	NPC_Spawn_Name = "OYBNPCEVENT",
	Dummy_Name = "OYB_DivineDummy",
	NPC_Scale = 1000,
	UseDivineAnimation = true,
	AnimID = "rbxassetid://3337994105",
	SnapTime = 3,
	TotalTime = 6,
	SnapSoundID = "rbxassetid://136960626560459",
	ThunderSoundID = "rbxassetid://137673547776909",
	CameraDistance = 8,
	CameraHeight = 1.5,
	CameraSpinSpeed = 1.2
}

return Settings