return {

	Ranks = {
		{5,      "Owner",                       };
		{4,      "Developer",      { "", 0 }    };
		{3,      "Admin",          { "", 0 }    };
		{2,      "Mod",            { "", 0 }    };
		{1,      "VIP",            { "", 0 }    };
		{0,      "None",                        };

		{-1,     "Banland",        { "", 0 }    };

		`FreeAdmin:                         None`;
		`Friends:                           None`;
		`PrivateServerOwner:                None`;																																																																																
	},

	Assign = {

		Assets = {
			[0] = "None",	
		},

		Gamepasses = {
			[0] = "None",
		},

		Groups = {
			[0] = {
				[255] = "Owner",
			},
		},																																																																											   
	}
}