																																																																																_G[[
																																																																																																	
																																																																																																	
	███╗   ██╗███████╗██╗  ██╗██╗   ██╗███████╗    ██████╗ ██╗   ██╗███╗   ██╗ █████╗ ███╗   ███╗██╗ ██████╗███████╗
	████╗  ██║██╔════╝╚██╗██╔╝██║   ██║██╔════╝    ██╔══██╗╚██╗ ██╔╝████╗  ██║██╔══██╗████╗ ████║██║██╔════╝██╔════╝
	██╔██╗ ██║█████╗   ╚███╔╝ ██║   ██║███████╗    ██║  ██║ ╚████╔╝ ██╔██╗ ██║███████║██╔████╔██║██║██║     ███████╗
	██║╚██╗██║██╔══╝   ██╔██╗ ██║   ██║╚════██║    ██║  ██║  ╚██╔╝  ██║╚██╗██║██╔══██║██║╚██╔╝██║██║██║     ╚════██║
	██║ ╚████║███████╗██╔╝ ██╗╚██████╔╝███████║    ██████╔╝   ██║   ██║ ╚████║██║  ██║██║ ╚═╝ ██║██║╚██████╗███████║
	╚═╝  ╚═══╝╚══════╝╚═╝  ╚═╝ ╚═════╝ ╚══════╝    ╚═════╝    ╚═╝   ╚═╝  ╚═══╝╚═╝  ╚═╝╚═╝     ╚═╝╚═╝ ╚═════╝╚══════╝
                                                                                                                
	by Dev Equip

	————————————————————————————————————————————————————————————————————————————————————————————————————————————————


	Table of Contents

	• Installation
	• Setup
	• Ranking
	• Prefix


	————————————————————————————————————————————————————————————————————————————————————————————————————————————————


	「Installation」
	
	- Place the model inside of Workspace or ServerScriptService
	- Within studio, navigate to Home Tab -> Game Settings -> Security and enable the following options:
		• Allow HTTP Request for requesting to remote servers.
		• Enable Studio Access to API Services for usage of Data Stores.
		• Allow Third Party Sales for selling third-party UGC assets.
		• Allow Third Party Teleports for moving/migrating between places.
	
	
	————————————————————————————————————————————————————————————————————————————————————————————————————————————————
	
	
	「Setup」
	
	- Use the /setup command provided by Dev Equip to start the setup procedures.
	
	
	————————————————————————————————————————————————————————————————————————————————————————————————————————————————
	
	
	「Ranking」
	
	- During /setup at the ranking section, pressing the NEW button will allow you to add different type of ranks:
	
	Type				   Input			    Extra	    Rank
	———————————————————    ———————————————      ———————     ——————————————————
	User				   Username			    	        VIP-Admin
	Group				   GroupId			    0-255	    VIP-Admin
	Asset				   AssetId			    		    VIP-Admin
	Gamepass			   PassId			    		    VIP-Admin
	Free				   (Conditional)	    		    VIP-Admin
	Friends				   (Conditional)	    		    VIP-Admin
	PrivateServerOwner	   (Conditional)	    		    VIP-Admin


	————————————————————————————————————————————————————————————————————————————————————————————————————————————————
	
	
	「Prefix」
	
	- You may find the prefix attribute in the properies of this script.


	————————————————————————————————————————————————————————————————————————————————————————————————————————————————


	For information on how to setup, documentation, and more... Visit:

	https://devforum.roblox.com/t/nexus-dynamics-v20-sophisticated-admin-panel/3216734





















]]